services:
  - type: web
    name: mastercraft-project
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_PORTAL_API_URL
        value: https://api-dev.mastercraft-products.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
